### PR TITLE
BS-39 | Siva,Vijay | Publish openmrs-distro-bahmni with SNOMED image tags

### PR DESCRIPTION
**Pull request by vijayanandtwks**
https://bahmni.atlassian.net/jira/software/c/projects/BS/boards/49?selectedIssue=BS-39

Screenshot 2022-12-20 at 6 02 19 PM

### CODE REVIEW

**Comment by angshu** [comment]
is the PR to master intentional? @vijayanandtwks

**Comment by vijayanandtwks** [comment]
> is the PR to master intentional? @vijayanandtwks

The PR was intended for snomed-master. Have changed it to snomed-master @angshu

**Comment by gsluthra** [comment]
Instead of updating the original build file, why not introduce a different one (`build_publish_openmrs_snomed.yml`)? When you will raise a PR for master branch(one day), you will need to then "skip" this file otherwise, since we won't merge these changes into master. What do u think?

**Comment by sivareddytw** [comment]
> Instead of updating the original build file, why not introduce a different one (`build_publish_openmrs_snomed.yml`)? When you will raise a PR for master branch(one day), you will need to then "skip" this file otherwise, since we won't merge these changes into master. What do u think?

@gsluthra we thought of skipping this file during merging with `master` branch. we thought of not to change/add any GHA during merge process.

**Review by gsluthra — APPROVED** [review]

**Pull request merged**
