### PR TITLE
Siva Reddy | BAH-2464 | Adding Dependency of bahmni-commons

### PR DESCRIPTION
**Pull request by sivareddytw**
JIRA - [https://bahmni.atlassian.net/browse/BAH-2464](https://bahmni.atlassian.net/browse/BAH-2464)

### CODE REVIEW

**Comment by binduak** [comment]
@sivareddytw the bahmnicommons.omod that you uploaded might be different from the one the gets out once the PR merged.  you can update this PR once the PR to bahmnicommons is merged ?

**Comment by sivareddytw** [comment]
> also this needs to be added to the distro pom.xml

pom.xml updated with bahmni-commons dependency

**Comment by binduak** [comment]
lets merge the PR once the [https://github.com/Bahmni/openmrs-module-bahmnicommons/pull/13/commits](https://github.com/Bahmni/openmrs-module-bahmnicommons/pull/13) is merged

**Review by binduak — APPROVED** [review]

**Review by angshu — APPROVED** [review]

**Comment by angshu** [comment]
Dont merge till bahmnicommons-1.0.0-snapshot is released

**Pull request merged**
